library(tidyverse)
library(ggplot2)

weakprom_weakRBS <-read_tsv("weakprom-weakRBS.txt")
weakprom_weakRBS$species<-recode(weakprom_weakRBS$species, "fluorescent-weak-RBS"="weak-prom-weak-RBS")
WW = data.frame()
WW <- filter(weakprom_weakRBS, species == "weak-prom-weak-RBS")
WW2 <- filter(weakprom_weakRBS, species =="__ribosome")
WW2 = WW2 %>% rename(free_ribosomes = protein)
weakweak <- full_join(WW, WW2, by ="time")
weakweak = weakweak %>% rename(ribo_density = ribo_density.x)
weakweak$burden = (weakweak$ribo_density*weakweak$transcript.x)
wpwr <- select(weakweak, burden, species.x, protein)

weakprom_medRBS <- read_tsv("weakprom-medRBS.txt")
weakprom_medRBS$species <-recode(weakprom_medRBS$species, "fluorescent-medium-RBS" = "weak-prom-med-RBS")
WM = data.frame()
WM <- filter(weakprom_medRBS, species == "weak-prom-med-RBS")
WM2 <- filter(weakprom_medRBS, species =="__ribosome")
WM2 = WM2 %>% rename(free_ribosomes = protein)
weakmed <- full_join(WM, WM2, by ="time")
weakmed = weakmed %>% rename(ribo_density = ribo_density.x)
weakmed$burden = (weakmed$ribo_density*weakmed$transcript.x)
wpmr <- select(weakmed, burden, species.x, protein)

weakprom_strongRBS <- read_tsv("weakprom-strongRBS.txt")
weakprom_strongRBS$species <-recode(weakprom_strongRBS$species, "fluorescent-strong-RBS" = "weak-prom-strong-RBS")
WS = data.frame()
WS <- filter(weakprom_strongRBS, species == "weak-prom-strong-RBS")
WS2 <- filter(weakprom_strongRBS, species =="__ribosome")
WS2 = WS2 %>% rename(free_ribosomes = protein)
weakstrong <- full_join(WS, WS2, by ="time")
weakstrong = weakstrong %>% rename(ribo_density = ribo_density.x)
weakstrong$burden = (weakstrong$ribo_density*weakstrong$transcript.x)
wpsr <- select(weakstrong, burden, species.x, protein)

strongprom_weakRBS <- read_tsv("strongprom-weakRBS.txt")
strongprom_weakRBS$species <-recode(strongprom_weakRBS$species, "fluorescent-weak-RBS" = "strong-prom-weak-RBS")
SW = data.frame()
SW <- filter(strongprom_weakRBS, species == "strong-prom-weak-RBS")
SW2 <- filter(strongprom_weakRBS, species =="__ribosome")
SW2 = SW2 %>% rename(free_ribosomes = protein)
strongweak <- full_join(SW, SW2, by ="time")
strongweak = strongweak %>% rename(ribo_density = ribo_density.x)
strongweak$burden = (strongweak$ribo_density*strongweak$transcript.x)
spwr <- select(strongweak, burden, species.x, protein)

strongprom_medRBS <- read_tsv("strongprom-medRBS.txt")
strongprom_medRBS$species <-recode(strongprom_medRBS$species, "fluorescent-medium-RBS" = "strong-prom-med-RBS")
SM = data.frame()
SM <- filter(strongprom_medRBS, species == "strong-prom-med-RBS")
SM2 <- filter(strongprom_medRBS, species =="__ribosome")
SM2 = SM2 %>% rename(free_ribosomes = protein)
strongmed <- full_join(SM, SM2, by ="time")
strongmed = strongmed %>% rename(ribo_density = ribo_density.x)
strongmed$burden = (strongmed$ribo_density*strongmed$transcript.x)
spmr <- select(strongmed, burden, species.x, protein)

strongprom_strongRBS <- read_tsv("strongprom-strongRBS.txt")
strongprom_strongRBS$species <-recode(strongprom_strongRBS$species, "fluorescent" = "strong-prom-strong-RBS")
SS = data.frame()
SS <- filter(strongprom_strongRBS, species == "strong-prom-strong-RBS")
SS2 <- filter(strongprom_strongRBS, species =="__ribosome")
SS2 = SS2 %>% rename(free_ribosomes = protein)
strongstrong <- full_join(SS, SS2, by ="time")
strongstrong = strongstrong %>% rename(ribo_density = ribo_density.x)
strongstrong$burden = (strongstrong$ribo_density*strongstrong$transcript.x)
spsr <- select(strongstrong, burden, species.x, protein)

bigdata = bind_rows(wpwr, wpmr)
bigdata2 = bind_rows(wpsr, spwr)
bigdata3 = bind_rows(spmr, spsr)
bigdata4 = bind_rows(bigdata, bigdata2)
bigdata5 = bind_rows(bigdata3, bigdata4)
bigdata5 = bigdata5 %>% rename(species = species.x)

ggplot(bigdata5, aes(burden, fill = species)) +
  geom_histogram()
